### PR TITLE
Add Image Support

### LINKED ISSUE #12: Gemini Models don't support attachments
```
LLM Model: openrouter/google/gemini-flash-1.5-8b-exp
Error: This model does not support attachments, but some were provided
```
I am trying to feed this model some mp3s.

### PR DESCRIPTION
**Pull request by montasaurus**
Adds support for image attachments on the OpenRouter models that support image input, fixes #12 .

We parse the `architecture.modality` field from the OpenRouter models payload to determine which models support image input. Adds tests with VCR cassettes for text and image prompting.

I used [inline-snapshot](https://simonwillison.net/2024/Apr/16/inline-snapshot/) for snapshotting the LLM payloads (h/t @simonw) and it makes updating the snapshots super easy.

Also bumped the Python versions to match [simonw/llm-claude-3](https://github.com/simonw/llm-claude-3).

### CODE REVIEW

**Comment by newptcai** [comment]
Can we merge this?

**Comment by simonw** [comment]
I'm getting this error on basically all models:
```bash
llm -m openrouter/openai/gpt-4 hi
```

> `Error: Completions.create() got an unexpected keyword argument 'stream_options'`

**Comment by simonw** [comment]
Oh interesting - running this fixed it:
```bash
llm install -U openai
```
That took me from openai1.25.1 up to openai-1.57.0 in my environment.

I'm going to pin to that as a dependency of this package.

**Comment by simonw** [comment]
OK, this is working for me now:
```bash
llm -m openrouter/anthropic/claude-3.5-sonnet describe -a https://static.simonwillison.net/static/2024/pelicans.jpg
```

> This image shows a large gathering of pelicans and other water birds clustered together on what appears to be a rocky shoreline next to water. The birds are densely packed, creating a mass of brown and grey feathers. You can see their distinctive long beaks and throat pouches characteristic of pelicans. The water in the background appears calm and dark. It's quite a remarkable sight to see so many of these large birds congregated in one place, which is something that often occurs during feeding times or at communal resting spots.

**Comment by newptcai** [comment]
Just tried this

> $ llm -m openrouter/amazon/nova-lite-v1 "create a concise caption" -a hotdog-5.webp 
> An exaggerated illustration of an extremely hot hot dog in a bun sitting on a checkered hot napkin with a chili pepper sitting next to it and a text that reads "Hottest hotdog in the universe" and flames surrounding it.

hotdog-5

**Pull request merged**
